### ISSUE TITLE
listening bar is not full witdh

### ISSUE THREAD

**Issue by IMBiXx** [NYRI4/Comfy-spicetify#1] opened 2021-11-08 13:10 UTC
Hi,
The listening bar is not full width at all:

![image](https://user-images.githubusercontent.com/9751045/140747557-e13372c2-d6e3-4aaf-8194-2df767cb9de4.png)

**Comment by NYRI4** [comment] 2021-11-10 17:20
I can't reproduce the issue on my client, you'll have to give more description, maybe try to disable some extensions to see if that could be the cause ?

**Comment by zaryavtre** [comment] 2021-11-17 16:31
The same thing is happening on my end. Disabled all extensions.

**Comment by afonsojramos** [comment] 2021-11-19 10:09
@IMBiXx @zaryavtre it is not happening on my end. Maybe update the theme? Also, can you share you config files?

**Comment by TheGeeKing** [comment] 2021-11-21 21:15
@IMBiXx @zaryavtre any update on that issue? If you still encounter that issue, please send your config file.

**Comment by zaryavtre** [comment] 2021-11-24 13:52
For me, you can close this issue now. After new updates it started working as expected.

**Comment by TheGeeKing** [comment] 2021-11-24 18:49
@NYRI4 you can close this issue.

**Closed** 2021-11-27 11:50 UTC
Labels: bug
